### PR TITLE
Extension of the Scoring Models and PTMs Scoring system

### PR DESCRIPTION
**Pull request by ypriverol**

### CODE REVIEW

**Comment by julianu** [comment]
* there are compilation failures in the PR, please solve them (preverably without editing the ReportPSMSet and other involved base classes, but the ones that introduced the problems)
* I saw you using ScoreXML to pass arguments and use it as as score. Please change this and try to use the Score class. ScoreXML is intended for PIA-XML parsing and writing only

**Comment by ypriverol** [comment]
You mean ScoreModel?

**Comment by ypriverol** [comment]
I have changed the ScoreXML to ScoreModel

**Comment by julianu** [comment]
Hej, I am now almost completely back to work but found some small issues remaining:

* All the cvLabel things you introduced: are they really necessary? Usually, until now, they were encoded in PIA like "MS:XXXX" or "UNIMOD:XXX" where MS or UNIMOD actually was the cvLabel and thus is easy to write out again (in e.g. mzTab). For all cases, the accessions were mapped to these two CVs, if they could not be used directly. I would prefer to keep it this way, unless you have a good reason to change this behavior.

* the modification probabilities: why are they a score and a list? Should it not suffice to have a simple double or float value for each PTM at a given position? (Actually there is one point: PIA currently does not support multiple PTMs at the same position. But that is something that should be implemented in the near future.) 

* the probabilities at all: as far as I know, a PTM probability only occurs when comparing multiple PSMs for the same spectrum, right? Therefore, the modification probabilities therefore should only occur in the PSMSets in PIA. But as this makes no big impact anywhere later in the inference pipeline, I am fine with it for now.

**Comment by ypriverol** [comment]
1- mztab has support for modifications like CHEMOD Ids or neutral losses. Then I would rather keep the CV label. Neutral losses, for example, can be called like MS as cvlabel or PSI-MS, for this reason, I keep the cvLabel. The other problem is than in the metadata you need this CVlabel to be annotated. 

2- We have already mztab cases that contain multiple probabilities score systems in the modification site, like for example FDR and PhosphoRS, the current model would be more open for this in the future. You should take into account that this will support future cases in a better way. 

3- OK.

**Pull request merged**
