### PR TITLE
Some refinements and clean of the code including dependencies and Java 8 

### PR DESCRIPTION
**Pull request by ypriverol**

### CODE REVIEW

**Comment by ypriverol** [comment]
@julianu can you check this.

**Comment by julianu** [comment]
Please only submit the pom updates first, not changes all around the source code.

**Comment by ypriverol** [comment]
@julianu all the code pass the corresponding tests. Most of the updates are refinements to the documentation, empty code, etc. what do you want me to do?

**Comment by julianu** [comment]
It did not pass the building on Travis.
Therefore I suggest we add it in smaller pieces, starting with e.g. the pom file.

**Comment by ypriverol** [comment]
I will Check why is not passing

**Comment by julianu** [comment]
Otherwise I will at least update the maven dependencies later today, so at least the compilation should work again. But as you already did this, I am happy to take your version.

**Comment by ypriverol** [comment]
Please leave it to me. I will check why is failing and do a PR.

**Pull request closed without merging**
