### PR TITLE
Adding FDR

### PR DESCRIPTION
**Pull request by ypriverol**
This PR adds the decoy information present in the PeptideEvidences to the PIA PSM.

### CODE REVIEW

**Comment by ypriverol** [comment]
I will do it

**Comment by ypriverol** [comment]
DONE

**Comment by julianu** [comment]
Almost, but it should not assign the decoy state, if no decoy information at all is given.

**Comment by ypriverol** [comment]
This is more complex because if no decoy information is given mzIdentML assume that the peptide is a target. I have no way to know if that information is present or not without modifying the mzIdentML code.. see how `isDecoy` is implemented: 

```
    public boolean isIsDecoy() {
        if (isDecoy == null) {
            return false;
        } else {
            return isDecoy;
        }
    }
```

**Pull request merged**
